name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/polimaster/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Define variables
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "tag=$tag" >> "$GITHUB_ENV"
          echo "src=src/Polimaster.Device.Transport.Usb/Polimaster.Device.Transport.Win.Usb" >> "$GITHUB_ENV"
      - name: Add github packages
        run: dotnet nuget update source github.polimaster -s "$src" -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Build
        run: dotnet build "$src" -c Release -p:AssemblyVersion="$tag" -p:Version="$tag"
#      - name: Run tests
#        run: dotnet test "$src.Tests"
      - name: Create the package
        run: dotnet pack "$src" -c Release -p:AssemblyVersion="$tag" -p:Version="$tag"
      - name: Publish the package to GPR
        run: dotnet nuget push "$src/bin/Release/*.nupkg"
